name             'loadtester_host'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures docker_host'
long_description 'Installs/Configures docker_host'
version          '0.3.2'

depends 'docker'
depends 'lvm'
depends 'ohai'
depends 'hostsfile'
