name             'loadtester_host'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures docker_host'
long_description 'Installs/Configures docker_host'
version          '0.2.1'

depends 'docker'
depends 'ohai'
depends 'hostsfile'
