name             'loadtester_guest'
maintainer       'Irving Popovetsky'
maintainer_email 'irving@getchef.com'
license          'All rights reserved'
description      'Installs/Configures loadtester_guest'
long_description 'Installs/Configures loadtester_guest'
version          '0.2.1'

depends 'chef-client'
depends 'push-jobs'
