name             'loadtester_guest'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures loadtester_guest'
long_description 'Installs/Configures loadtester_guest'
version          '0.2.1'

depends 'chef-client'
depends 'push-jobs'
