name             'docker_host'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures docker_host'
long_description 'Installs/Configures docker_host'
version          '0.1.5'

depends 'docker'
depends 'ohai'